version: '3'
services:
  app:
    container_name: sneaker-api
    build: .
    volumes:
      - ./sneak-sneaker-api:/usr/src/app
      - ./sneak-sneaker-api/start.sh:/usr/src/app/start.sh
    ports:
      - "3000:3000"
    environment:
      - HOST=mysql
      - PORT=3306
      - DATABASE=sneakpeak
      - USERNAME=root
      - PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: ["/bin/bash", "/usr/src/app/start.sh"]
    depends_on:
      - mysql
  mysql:
    container_name: sneaker-api-db
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: sneakpeak
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
volumes:
  db_data:

