name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
    	fetch-depth: 0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build and run API Docker Container
      run: MYSQL_ROOT_PASSWORD=test_password docker compose up --build -d
    - name: Install dependencies
      run: yarn install
      working-directory: ./sneak-sneaker-api  
    - name: Wait for API to fully initialize
      run: sleep 15
    - name: Run tests
      run: docker exec sneaker-api yarn test
    - name: SonarCloud run
      uses: sonarsource/sonarcloud-github-action@master
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
